### ISSUE TITLE
Unable to fetch Grafana Alerts in Concourse and folders not being created for normal alerts

### ISSUE THREAD

**Issue by dipeshtripathi** [varmakarthik12/slack-chat-resource#3]
Hi, I am trying to use this resource for automating service recovery and using Grafana Alerts as trigger.
Although I can see that grafana posted an alert on Slack, the message content comes up empty in concourse.
Also, when I manually type the message, although I can see the message in concourse, it doesnt create the files associated.
I am fairly new to Concourse and would appreciate any/all the help!
<img width="606" alt="Screenshot 2021-03-10 at 16 13 00" src="https://user-images.githubusercontent.com/65688344/110617728-06a14880-81bc-11eb-8802-8de8711e03f5.png">

<img width="505" alt="Screenshot 2021-03-10 at 16 12 06" src="https://user-images.githubusercontent.com/65688344/110617726-05701b80-81bc-11eb-9ead-c97f22d08d86.png">

Below is my code.
resource_types:
    - name: slack-read-resource
      type: docker-image
      source:
        repository: varmakarthik12/slack-read-resource

resources:
  - name: slack-in
    type: slack-read-resource
    source:
      token: "token"
      channel_id: "channel ID"
      #matching:
        #text_pattern: '<@U01QH5B0MGA>\s+(.+)'
      

jobs:
  - name: test
    public: true
    plan:
      - get: slack-in
        trigger: true
        #params:
         #text_pattern: '<@U01QH5B0MGA> ([A-Z]+) ([0-9]+)'
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          run:
            path: /bin/sh
            args: 
            - -c
            - |
              echo "We did it! Task was triggered"
              ls -a ../
              ls -a .

**Comment by varmakarthik12** [comment]
@dipeshtripathi  can u make sure u have the correct Textpattern with the correct botID. Also, I noticed u should have  `slack-in` as an input to ur task. U can reuse it by creating a resource something like this.

```
resources:
- name: slack-in
  icon: slack
  check_every: 15s
  type: slack-read-resource
  source:
      token: ((bot-details.token))
      channel_id: ((bot-details.channel_id))
      matching:
        text_pattern: <@((bot-details.user_id))>\s+(.+)
      not_replied_by:
        author: ((bot-details.user_id))
```
And reuse the same on the JOB something like this.

```
jobs:
- name: some-name
  plan:
  - get: slack-in
    trigger: true
  - task: some-task
    config:
      inputs:
      - name: slack-in
      platform: linux
      image_resource:
        source:
          repository: node
        type: docker-image
      run:
```
